### ISSUE TITLE
previewAuto cause error on Windows 10 system,previewSite works

### ISSUE THREAD

**Issue by hepin1989** [sbt/sbt-site#118]
```
IJ]sbt:PragmaticScala> previewAuto
[error] java.nio.file.NoSuchFileException: C:\Users\kerr\IdeaProjects\Pragmatic-Scala\src\main\scala-2.12
[error]         at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
[error]         at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[error]         at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[error]         at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
[error]         at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
[error]         at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
[error]         at java.nio.file.Files.readAttributes(Files.java:1737)
[error]         at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
[error]         at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
[error]         at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
[error]         at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
[error]         at java.nio.file.Files.find(Files.java:3687)
[error]         at com.typesafe.sbt.site.Compat$.$anonfun$genSources$3(Compat.scala:41)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error]         at scala.collection.immutable.List.flatMap(List.scala:352)
[error]         at com.typesafe.sbt.site.Compat$.$anonfun$genSources$2(Compat.scala:33)
[error]         at com.typesafe.sbt.site.Preview$.apply(preview.scala:15)
[error]         at com.typesafe.sbt.site.SitePreviewPlugin$.$anonfun$projectSettings$4(SitePreviewPlugin.scala:46)
[error]         at com.typesafe.sbt.site.SitePreviewPlugin$.$anonfun$projectSettings$4$adapted(SitePreviewPlugin.scala:42)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (*:previewAuto) java.nio.file.NoSuchFileException: C:\Users\kerr\IdeaProjects\Pragmatic-Scala\src\main\scala-2.12
```

**Comment by jonas** [comment]
Reproducible on macOS also:

```
sbt:sbt-site> previewAuto
[error] java.nio.file.NoSuchFileException: /opt/sbt-site/src/main/scala-2.12
[error] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[error] 	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[error] 	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
[error] 	at java.nio.file.Files.readAttributes(Files.java:1737)
[error] 	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
[error] 	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
[error] 	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
[error] 	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
[error] 	at java.nio.file.Files.find(Files.java:3687)
[error] 	at com.typesafe.sbt.site.Compat$.$anonfun$genSources$3(Compat.scala:41)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at com.typesafe.sbt.site.Compat$.$anonfun$genSources$2(Compat.scala:33)
[error] 	at com.typesafe.sbt.site.Preview$.apply(preview.scala:15)
[error] 	at com.typesafe.sbt.site.SitePreviewPlugin$.$anonfun$projectSettings$4(SitePreviewPlugin.scala:46)
[error] 	at com.typesafe.sbt.site.SitePreviewPlugin$.$anonfun$projectSettings$4$adapted(SitePreviewPlugin.scala:42)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (previewAuto) java.nio.file.NoSuchFileException: /opt/sbt-site/src/main/scala-2.12
```
