### ISSUE TITLE
Empty Site or StringTemplate 'page' was not found

### ISSUE THREAD

**Issue by jeschkies** [sbt/sbt-site#159]
Hi :wave: 

I have the following multi project setup [setup](https://github.com/mesosphere/usi/pull/146):
```
lazy val `root` = (project in file("./"))
  .settings(
    commonSettings,
    publish / skip := true)
  .enablePlugins(ScalaUnidocPlugin, GhpagesPlugin, ParadoxSitePlugin)
  .settings(
    // Documentation
    paradoxTheme := Some(builtinParadoxTheme("generic")),
    paradox / sourceDirectory := baseDirectory.value / "docs",
    siteSubdirName in ScalaUnidoc := "api",
    addMappingsToSiteDir(mappings in (ScalaUnidoc, packageDoc), siteSubdirName in ScalaUnidoc),
    gitRemoteRepo := "git@github.com:mesosphere/usi.git"
  )
  .aggregate(...)
```
The `Markdown files are in `./docs`. When I run `sbt makeSite` the dir `target/site` only includes the generate API documentation from unidoc and a `paradox.json`. What's wrong with the setup?

However, if I put a simple Markdown file in `src/main/paradox` I get the following error
```
[error] java.lang.RuntimeException: StringTemplate 'page' was not found for 'usi/target/paradox/html/main/index.html'. Create a template or set a theme that contains one.

```

**Comment by ennru** [comment]
There is something not quite right with Paradox' `sourceDirectory` setting https://github.com/lightbend/paradox/issues/423

**Comment by jeschkies** [comment]
@ennru, thanks! That solves the source issue. However, now I have this error
```
[error] java.lang.RuntimeException: StringTemplate 'page' was not found for '/Users/kjeschkies/src/usi/target/paradox/html/main/index.html'. Create a template or set a theme that contains one.
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at com.lightbend.paradox.template.PageTemplate.write(PageTemplate.scala:44)
...
```

**Comment by jeschkies** [comment]
When I define a new subproject it works. It must be something defined in `commonSettings`.

**Comment by jeschkies** [comment]
I just removed the `commonSettings`.
