### ISSUE TITLE
errors when using OpenJDK 16

### ISSUE THREAD

**Issue by mr-git** [sbt/sbt-site#169]
```
[error] java.lang.RuntimeException: Error creating extended parser class: Could not determine whether class 'org.pegdown.ParserWithDirectives$$parboiled' has already been loaded
[error]         at org.parboiled.Parboiled.createParser(Parboiled.java:58)
[error]         at com.lightbend.paradox.markdown.Reader.<init>(Reader.scala:40)
[error]         at com.lightbend.paradox.ParadoxProcessor$.$lessinit$greater$default$1(ParadoxProcessor.scala:30)
[error]         at com.lightbend.paradox.sbt.ParadoxPlugin$.$anonfun$paradoxSettings$1(ParadoxPlugin.scala:58)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:831)
[error] Caused by: java.lang.RuntimeException: Could not determine whether class 'org.pegdown.ParserWithDirectives$$parboiled' has already been loaded
[error]         at org.parboiled.transform.AsmUtils.findLoadedClass(AsmUtils.java:213)
[error]         at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:35)
[error]         at org.parboiled.Parboiled.createParser(Parboiled.java:54)
[error]         at com.lightbend.paradox.markdown.Reader.<init>(Reader.scala:40)
[error]         at com.lightbend.paradox.ParadoxProcessor$.$lessinit$greater$default$1(ParadoxProcessor.scala:30)
[error]         at com.lightbend.paradox.sbt.ParadoxPlugin$.$anonfun$paradoxSettings$1(ParadoxPlugin.scala:58)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:831)
[error] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @1d1e905
[error]         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[error]         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[error]         at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[error]         at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[error]         at org.parboiled.transform.AsmUtils.findLoadedClass(AsmUtils.java:206)
[error]         at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:35)
[error]         at org.parboiled.Parboiled.createParser(Parboiled.java:54)
[error]         at com.lightbend.paradox.markdown.Reader.<init>(Reader.scala:40)
[error]         at com.lightbend.paradox.ParadoxProcessor$.$lessinit$greater$default$1(ParadoxProcessor.scala:30)
[error]         at com.lightbend.paradox.sbt.ParadoxPlugin$.$anonfun$paradoxSettings$1(ParadoxPlugin.scala:58)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:831)
[error] java.lang.RuntimeException: Error creating extended parser class: Could not determine whether class 'org.pegdown.ParserWithDirectives$$parboiled' has already been loaded
[error]         at org.parboiled.Parboiled.createParser(Parboiled.java:58)
[error]         at com.lightbend.paradox.markdown.Reader.<init>(Reader.scala:40)
[error]         at com.lightbend.paradox.ParadoxProcessor$.$lessinit$greater$default$1(ParadoxProcessor.scala:30)
[error]         at com.lightbend.paradox.sbt.ParadoxPlugin$.$anonfun$paradoxSettings$1(ParadoxPlugin.scala:58)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:831)
[error] Caused by: java.lang.RuntimeException: Could not determine whether class 'org.pegdown.ParserWithDirectives$$parboiled' has already been loaded
[error]         at org.parboiled.transform.AsmUtils.findLoadedClass(AsmUtils.java:213)
[error]         at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:35)
[error]         at org.parboiled.Parboiled.createParser(Parboiled.java:54)
[error]         at com.lightbend.paradox.markdown.Reader.<init>(Reader.scala:40)
[error]         at com.lightbend.paradox.ParadoxProcessor$.$lessinit$greater$default$1(ParadoxProcessor.scala:30)
[error]         at com.lightbend.paradox.sbt.ParadoxPlugin$.$anonfun$paradoxSettings$1(ParadoxPlugin.scala:58)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:831)
[error] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @1d1e905
[error]         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[error]         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[error]         at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[error]         at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[error]         at org.parboiled.transform.AsmUtils.findLoadedClass(AsmUtils.java:206)
[error]         at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:35)
[error]         at org.parboiled.Parboiled.createParser(Parboiled.java:54)
[error]         at com.lightbend.paradox.markdown.Reader.<init>(Reader.scala:40)
[error]         at com.lightbend.paradox.ParadoxProcessor$.$lessinit$greater$default$1(ParadoxProcessor.scala:30)
[error]         at com.lightbend.paradox.sbt.ParadoxPlugin$.$anonfun$paradoxSettings$1(ParadoxPlugin.scala:58)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by LeifW** [comment]
See also https://github.com/lightbend/paradox/issues/491

**Comment by SethTisue** [comment]
comment with possible workarounds: https://github.com/sirthias/parboiled/issues/175#issuecomment-878331837

**Comment by xuwei-k** [comment]
- https://github.com/sirthias/parboiled/pull/195
- https://github.com/lightbend/paradox/blob/7ef1d3250743ec25b6ff3439ad31083724b28979/project/Dependencies.scala#L23
- https://github.com/lightbend/paradox/commit/5413555ebc62e7300f639a854bea94e8cc2ba6a3
- https://github.com/lightbend/paradox/issues/491
